<?php
namespace grozzzny\companies;

use grozzzny\companies\assets\ModuleAsset;
use Yii;
use yii\easyii2\components\FastModule;

class Module extends FastModule
{
    public $settings = [
        'modelCompany' => '',
    ];

    public $controllerMap = [
        'ajax' => 'grozzzny\companies\controllers\AjaxController',
        'a' => 'yii\easyii2\controllers\FastController',
    ];

    public function init()
    {
        //self::setView('@grozzzny/companies/views');

        self::registerTranslation();

        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function registerAssets()
    {
        ModuleAsset::register(Yii::$app->view);
    }

    public static function registerTranslation()
    {
        Yii::$app->i18n->translations['gr*'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@grozzzny/companies/messages',
        ];
    }

    public $title = 'Companies';
    public $icon = 'file';

    public function getTitle()
    {
        // TODO: Implement getTitle() method.
        return Yii::t('app', $this->title);
    }

    public function getName()
    {
        // TODO: Implement getName() method.
        return $this->id;
    }

    public function getIcon()
    {
        // TODO: Implement getIcon() method.
        return $this->icon;
    }

}