<?php
namespace grozzzny\companies;

use grozzzny\companies\assets\ModuleAsset;
use Yii;

class Module extends \grozzzny\base_module\Module
{
    public $settings = [
        'modelCompany' => '',
    ];

    public $controllerMap = [
        'ajax' => 'grozzzny\companies\controllers\AjaxController',
    ];

    public function init()
    {
        self::setView('@grozzzny/companies/views');

        self::registerTranslation();

        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function registerAssets()
    {
        parent::registerAssets(); // TODO: Change the autogenerated stub

        ModuleAsset::register(Yii::$app->view);
    }

    public static function registerTranslation()
    {
        Yii::$app->i18n->translations['gr*'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@grozzzny/companies/messages',
        ];
    }

    protected static function setView($view)
    {
        $pathMap = Yii::$app->view->theme->pathMap;

        if(key_exists('@grozzzny/base_module/views', $pathMap)){
            array_push(Yii::$app->view->theme->pathMap['@grozzzny/base_module/views'], $view);
        }else{
            Yii::$app->view->theme->pathMap['@grozzzny/base_module/views'] = $view;
        }
    }
}